/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.ArticleDAO;
import edu.esprit.sweet4u.DAO.CommandeDAO2;
import edu.esprit.sweet4u.DAO.PanierDAO;
import edu.esprit.sweet4u.entites.ArticlePanier;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import edu.esprit.sweet4u.GUI.PanierModel;
import edu.esprit.sweet4u.entites.Commande;
import edu.esprit.sweet4u.entites.Panier;
import static java.util.Collections.list;
import java.util.Iterator;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author WiKi
 */
public class AfficherPanier extends javax.swing.JFrame {
    //static int id_cmde;
    int row;
    AbstractTableModel model;
    ArrayList<ArticlePanier> list;
    //int id_cmde=0;

    /**
     * Creates new form AfficherPanier
     */
    public AfficherPanier() {
       
        initComponents();
        model = (AbstractTableModel) jTable1.getModel();

        RefineryUtilities.centerFrameOnScreen(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tfQuantite = new javax.swing.JTextField();
        ModifierQuantite = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        supprimer = new javax.swing.JButton();
        Commander = new javax.swing.JButton();
        retourDuPanierAuArticles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new PanierModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ModifierQuantite.setText("ModifierQuantite");
        ModifierQuantite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ModifierQuantiteMouseReleased(evt);
            }
        });
        ModifierQuantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierQuantiteActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantité");

        jLabel3.setText("Kg");

        supprimer.setText("supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        Commander.setText("Commander");
        Commander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommanderActionPerformed(evt);
            }
        });

        retourDuPanierAuArticles.setText("Ajouter Un Autre Article");
        retourDuPanierAuArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourDuPanierAuArticlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModifierQuantite)
                        .addGap(46, 46, 46)
                        .addComponent(supprimer)
                        .addGap(26, 26, 26)
                        .addComponent(Commander))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(retourDuPanierAuArticles)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierQuantite)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(supprimer)
                    .addComponent(Commander))
                .addGap(18, 18, 18)
                .addComponent(retourDuPanierAuArticles)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierQuantiteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierQuantiteMouseReleased
        /*  PanierDAO pdao=new PanierDAO();
         row = jTable1.getSelectedRow();
         String nom = (jTable1.getModel().getValueAt(row, 0).toString());
         // tfQuantite.setText(Quantite); 
         // PersonneDAO pdao=new PersonneDAO(); // bon
         //String id=tfid.getText(); 
         ArticlePanier pan=new ArticlePanier();
         float qtte=Float.parseFloat(tfQuantite.getText());
         pan.setQuantite(qtte);
      
         //        pdao.updatePanier(pan, nom);
       
         // ArticlePanier pan =adao.AfficherPanier();
         /* 
         int indice=pan.getArticles().indexOf(id_article); //recupere l indice de qtte

         String s =tfQuantite.getText();
         float qtte=Float.parseFloat(s);
      
         float [] listeQuantites=pan.getQuantites();
         listeQuantites[indice]=qtte;
         pan.setQuantites(listeQuantites);
     
         //  adao.ModifierQuantiteArticlePanier(pan);       / jeudi */
        //JOptionPane.showMessageDialog(rootPane,"Quantité d'article modifiée");*/
    }//GEN-LAST:event_ModifierQuantiteMouseReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        tfQuantite.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 3)));


    }//GEN-LAST:event_jTable1MouseClicked

    private void ModifierQuantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierQuantiteActionPerformed

        PanierDAO pDAO = new PanierDAO();
        try {
            String nom = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
           
            float qte = Float.parseFloat(tfQuantite.getText());
            pDAO.modifierQuantite(nom, qte);

            JOptionPane.showMessageDialog(null, "quantité modifié avec succés");
            tfQuantite.setText(null);

            PanierModel panier = new PanierModel();
            jTable1.setModel(panier);
            panier.fireTableDataChanged();
            model = (AbstractTableModel) jTable1.getModel();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un article ");

        }

    }//GEN-LAST:event_ModifierQuantiteActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

        PanierDAO pDAO = new PanierDAO();
        try {
            String nom = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
            int id_A = pDAO.findArticleByNom(nom);
            pDAO.supprimerArticleDuPanier(nom);
            PanierModel panier = new PanierModel();
            jTable1.setModel(panier);
            panier.fireTableDataChanged();
            model = (AbstractTableModel) jTable1.getModel();
            tfQuantite.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un article ");

        }

    }//GEN-LAST:event_supprimerActionPerformed

    private void CommanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommanderActionPerformed

     
        //int id_c=1; // id du client connecté
        try {
            PanierDAO pDAO = new PanierDAO();
          
              Panier pan=new Panier();
            List<ArticlePanier> list=new ArrayList<ArticlePanier>(); 
                      list=pan.getListeArtPan();
                  
            System.out.println("liste="+list);
            String chaine_Id="0";
       for(ArticlePanier a: list) {
            pDAO.ajouterCommande(a);
            int id=pDAO.rechercherIdArticlePanier(a);
             chaine_Id=chaine_Id+","+id;
             
           System.out.println(a);
          
        }
       CommandeDAO2 cdao = new CommandeDAO2(); 
       cdao.ajouterChaineACommande(chaine_Id);
         /*   PanierModel panier = new PanierModel();
            jTable1.setModel(panier);
            panier.fireTableDataChanged();
            model = (AbstractTableModel) jTable1.getModel(); */

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Erreur d'ajout de Commande");

        }
    }//GEN-LAST:event_CommanderActionPerformed

    private void retourDuPanierAuArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourDuPanierAuArticlesActionPerformed
        this.setVisible(false);
        // AfficherArticles Panier = new AfficherArticles(); 
        new ListArticle().setVisible(true);
    }//GEN-LAST:event_retourDuPanierAuArticlesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherPanier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherPanier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherPanier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherPanier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AfficherPanier().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Commander;
    private javax.swing.JButton ModifierQuantite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton retourDuPanierAuArticles;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField tfQuantite;
    // End of variables declaration//GEN-END:variables
}
