/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.ClientDAO;
import edu.esprit.sweet4u.DAO.IClientDAO;
import edu.esprit.sweet4u.DAO.IPersonneDAO;
import edu.esprit.sweet4u.DAO.PersonneDAO;
import edu.esprit.sweet4u.DAO.ResponsablePatisserieDAO;
import edu.esprit.sweet4u.GUI.ModifierCompteClient;
import edu.esprit.sweet4u.GUI.modifCompteResponsable;
import edu.esprit.sweet4u.entites.Client;
import edu.esprit.sweet4u.entites.Personne;
import edu.esprit.sweet4u.entites.ResponsablePatisserie;
import edu.esprit.sweet4u.util.PersonneConenction;

/**
 *
 * @author Zeineb
 */
public class Authentification extends javax.swing.JFrame {
    static Personne personne;
    static ResponsablePatisserie responsable;
    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();
        connecter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        login.setForeground(new java.awt.Color(204, 204, 204));
        login.setText("Taper Votre Login ");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 64, 248, 34));

        pwd.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        pwd.setForeground(new java.awt.Color(204, 204, 204));
        pwd.setText("Taper Votre Mot de Passe ");
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        jPanel1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 129, 248, 33));

        connecter.setBackground(new java.awt.Color(255, 255, 255));
        connecter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        connecter.setText("Se connecter");
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });
        jPanel1.add(connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 226, -1, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("S'inscrire");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 485, 62, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed

        IPersonneDAO pdao = new PersonneDAO();
        IClientDAO cdao = new ClientDAO();
        Personne p =new Personne();
        Client c =new Client();
        
        
        p = pdao.FindPersonneByLogin(login.getText());
        int id_retour = p.getId();
        System.out.println(id_retour);
        int id_retourclient = cdao.returnID2(id_retour);
        System.out.println(id_retourclient);
        if (id_retourclient<=0)
            
        {  login.getText();
            PersonneConenction.setInstance(p);  //ajouter par MT Yassine
      // Personne p = pdao.FindPersonneByLogin(login.getText());
        this.personne=p;
        System.out.println(p);
            //ModifierCompteClient ac = new ModifierCompteClient();
            //EvoyerReclamation ac = new EvoyerReclamation();
        AcceuilClient ac=new AcceuilClient();
            
          //ac.setP(p);
          ac.setVisible(true);
          this.setVisible(false);
            
        }
        else if(id_retourclient>0)
        {
            PersonneConenction.setInstance(p);  //ajouter par MT Yassine 
            login.getText();
      // Personne p = pdao.FindPersonneByLogin(login.getText());
             ResponsablePatisserieDAO a = new ResponsablePatisserieDAO();
             
             this.personne=p;
             responsable = a.FindResponsableByLogin(p.getId());
             System.out.println(responsable);
        
           //modifCompteResponsable res = new modifCompteResponsable();
             //AjouterPatisserie res = new AjouterPatisserie();
          AcceuilResponsablePatisserie ar=new AcceuilResponsablePatisserie();
         ar.setVisible(true);
          this.setVisible(false);
            
            
        }
        
//        login.getText();
//      //  Personne p = pdao.FindPersonneByLogin(login.getText());
//        this.personne=p;
//        System.out.println(p);
//        
//        
//    
//     
//          ModifierCompteClient ac = new ModifierCompteClient();
//          ac.setP(p);
//          ac.setVisible(true);
//          this.setVisible(false);
     
    }//GEN-LAST:event_connecterActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JTextField pwd;
    // End of variables declaration//GEN-END:variables
}
