/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.CommentaireDAO;
import edu.esprit.sweet4u.DAO.PersonneDAO;
import edu.esprit.sweet4u.entites.Commentaire;
import edu.esprit.sweet4u.entites.Personne;
import edu.esprit.sweet4u.util.PersonneConenction;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Commentaires extends javax.swing.JFrame {

    /**
     * Creates new form Commentaires
     */
    public Commentaires(int id) {
        initComponents();
        // RefineryUtilities.centerFrameOnScreen(this);
        int id_a=id;
        NomEG.setText("Commentaires du produit");
        CommentaireDAO cDAO = new CommentaireDAO();
        PersonneDAO pDAO = new PersonneDAO();
        List<Commentaire> ListeEG = cDAO.afficherCommentaire(id); 
        System.out.println(ListeEG);
        DefaultTableModel dtm = new DefaultTableModel(); 
        dtm.addColumn("Nom");
        dtm.addColumn("Prenom");
        dtm.addColumn("Date");
        dtm.addColumn("Commentaire"); 
        try { 
            dtm.setRowCount(0);
            for (Commentaire c : ListeEG) {
            
                String Libelle = c.getCommentaire();
                String Date=c.getDatecom();
                Personne pe = pDAO.ChercherPersonneByID((c.getId_p()));
                String nom = pe.getNom();
                String prenom= pe.getPrenom();
                Object[] obj = {nom,prenom,Date,Libelle};
                dtm.addRow(obj); //Affectation de l'objet obj de type Tableau d'Object à notre model
            }
            jTable1.setModel(dtm); // Association du model à notre tableau nommé jTable2
        } catch (Exception e) {
            System.err.println("Erreur 5555555" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Valider = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomEG = new javax.swing.JLabel();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Signaler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date", "Commentaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 375, 190);

        Valider.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\btn1212.png")); // NOI18N
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(650, 530, 160, 50);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\annuler.png")); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(650, 350, 160, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(18, 521, 275, 20);

        jLabel1.setText("Commentaire");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 319, 90, 189);

        NomEG.setText("Commentaires ");
        getContentPane().add(NomEG);
        NomEG.setBounds(28, 8, 120, 14);

        Modifier.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\modifier.png")); // NOI18N
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        getContentPane().add(Modifier);
        Modifier.setBounds(650, 410, 160, 50);

        Supprimer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\Supprimer.png")); // NOI18N
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Supprimer);
        Supprimer.setBounds(650, 470, 160, 50);

        Signaler.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\signaler.png")); // NOI18N
        Signaler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignalerActionPerformed(evt);
            }
        });
        getContentPane().add(Signaler);
        Signaler.setBounds(311, 503, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\12131.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 830, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        PersonneDAO perDAO=new PersonneDAO();
        CommentaireDAO comDAO=new CommentaireDAO();
        if(!jTextField1.getText().equalsIgnoreCase("")){
        
            Commentaire comm=new Commentaire();
            comm.setId_a(2);
            comm.setId_p(/*personneInstance.getId()*/2);//a changer
           // comm.setDate("2018");
            comm.setCommentaire(jTextField1.getText());
            CommentaireDAO cdao=new CommentaireDAO();
            cdao.ajouterCommentaire(comm);
            
         this.setVisible(false);
         this.setVisible(true);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        // TODO add your handling code here:
        PersonneDAO perDAO= new PersonneDAO();
        CommentaireDAO comDAO = new CommentaireDAO();

           try {
            int row = jTable1.getSelectedRow();
            String compreced = jTable1.getModel().getValueAt(row, 3).toString();
            Personne p= PersonneConenction.getInstance();
            System.out.println(compreced);
            Commentaire c = new Commentaire();
            c= comDAO.trouverCommentaireParTxt(compreced);
            if (c.getId_p()==p.getId()){//a changer 
            c.setCommentaire(jTextField1.getText());
            comDAO.modifierCommentaire(c, c.getId());}
            else{
                JOptionPane.showMessageDialog(rootPane, " Vous ne pouvez modifier que vos propres commentaires ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un commentaire ");

        }
           List<Commentaire> ListeEG = comDAO.afficherCommentaire(2);// a changer
        System.out.println(ListeEG);
        DefaultTableModel dtm = new DefaultTableModel(); 
        dtm.addColumn("Nom");
        dtm.addColumn("Prenom");
        dtm.addColumn("Date");
        dtm.addColumn("Commentaire"); 
        try { 
            dtm.setRowCount(0);
            for (Commentaire c : ListeEG) {
            
                String Libelle = c.getCommentaire();
                String Datecom=c.getDatecom();
                Personne pe = perDAO.ChercherPersonneByID((c.getId_p()));
                String nom = pe.getNom();
                String prenom= pe.getPrenom();
                Object[] obj = {nom,prenom,Datecom,Libelle};
                dtm.addRow(obj); //Affectation de l'objet obj de type Tableau d'Object à notre model
            }
            jTable1.setModel(dtm); // Association du model à notre tableau nommé jTable2
        } catch (Exception e) {
            System.err.println("Erreur 5555555" + e.getMessage());
        }
        
    }//GEN-LAST:event_ModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed

        // TODO add your handling code here:
        CommentaireDAO comDAO = new CommentaireDAO();
        PersonneDAO perDAO=new PersonneDAO();
        try {
            Personne p= PersonneConenction.getInstance();
            int rows = jTable1.getSelectedRow();
            String a = jTable1.getModel().getValueAt(rows, 3).toString();
            Commentaire c= comDAO.trouverCommentaireParTxt(a);
            c.toString();
            if (c.getId_p()==p.getId()){// a changer
                
            comDAO.supprimerCommentare(c);}
            else {
                JOptionPane.showMessageDialog(rootPane, " Vous ne pouvez supprimer que vos commentaires");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un commentaire");

        }
       this.setVisible(false);
       this.setVisible(true);
    }//GEN-LAST:event_SupprimerActionPerformed

    private void SignalerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignalerActionPerformed
        // TODO add your handling code here:
        CommentaireDAO comDAO = new CommentaireDAO();
        try {
            int rows = jTable1.getSelectedRow();
            String a = jTable1.getModel().getValueAt(rows, 3).toString();
            Commentaire c= comDAO.trouverCommentaireParTxt(a);
            int id= c.getId();
            comDAO.signalerCommentaire(id);
        JOptionPane.showMessageDialog(rootPane, " Commentaire Signalé");
        }catch (Exception e)
                {
           JOptionPane.showMessageDialog(rootPane, " Probleme"); 
        }
    }//GEN-LAST:event_SignalerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commentaires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commentaires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commentaires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commentaires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commentaires(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifier;
    private javax.swing.JLabel NomEG;
    private javax.swing.JButton Signaler;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Valider;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
