/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.ClientDAO;
import edu.esprit.sweet4u.DAO.IClientDAO;
import edu.esprit.sweet4u.DAO.PersonneDAO;
import edu.esprit.sweet4u.DAO.ResponsablePatisserieDAO;
import edu.esprit.sweet4u.entites.Client;
import edu.esprit.sweet4u.entites.ResponsablePatisserie;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Zeineb
 */
public class CompteClient extends javax.swing.JFrame {

    /**
     * Creates new form CompteClient
     */
    public CompteClient() {
        initComponents();
        jPanel2.setVisible(false);
    }

    public static boolean isInteger(String s) {

        boolean v = false;
        try {
            Integer.parseInt(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nompatisserie = new javax.swing.JTextField();
        adressePatisserie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tnom = new javax.swing.JLabel();
        RBClient = new javax.swing.JRadioButton();
        RBRespo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tnomP = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomPatisserie = new javax.swing.JTextField();
        adressepatisserie = new javax.swing.JTextField();
        tadressep = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        tprenom = new javax.swing.JLabel();
        tcin = new javax.swing.JLabel();
        tlogin = new javax.swing.JLabel();
        tpwd = new javax.swing.JLabel();
        tdate = new javax.swing.JLabel();
        tadresse = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setEnabled(false);

        jLabel10.setText("Nom Pâtisserie : ");

        jLabel11.setText("Adresse Pâtisserie : ");

        adressePatisserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressePatisserieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(nompatisserie, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adressePatisserie)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nompatisserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adressePatisserie, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(807, 800));
        jPanel3.setLayout(null);

        tnom.setBackground(new java.awt.Color(255, 0, 0));
        tnom.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tnom);
        tnom.setBounds(183, 260, 184, 0);

        RBClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RBClient.setText("Client");
        RBClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBClientActionPerformed(evt);
            }
        });
        jPanel3.add(RBClient);
        RBClient.setBounds(30, 170, 142, 31);

        RBRespo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RBRespo.setText("Responsable Pâtisserie");
        RBRespo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBRespoActionPerformed(evt);
            }
        });
        jPanel3.add(RBRespo);
        RBRespo.setBounds(523, 170, 304, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("  Nom : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(23, 224, 47, 15);

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel3.add(nom);
        nom.setBounds(183, 222, 184, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("  Prenom : ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(23, 267, 67, 15);

        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prenomMouseEntered(evt);
            }
        });
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        jPanel3.add(prenom);
        prenom.setBounds(183, 267, 184, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("  CIN : ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(36, 319, 41, 15);

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });
        jPanel3.add(cin);
        cin.setBounds(183, 314, 184, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tnomP.setBackground(new java.awt.Color(255, 0, 0));
        tnomP.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Adresse Patisserie : ");

        nomPatisserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPatisserieActionPerformed(evt);
            }
        });

        adressepatisserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressepatisserieActionPerformed(evt);
            }
        });

        tadressep.setBackground(new java.awt.Color(255, 0, 0));
        tadressep.setForeground(new java.awt.Color(255, 0, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nom Patisserie : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tadressep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tnomP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adressepatisserie, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(nomPatisserie))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomPatisserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(tnomP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(adressepatisserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tadressep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(506, 222, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("  Login : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(36, 372, 54, 15);
        jPanel3.add(login);
        login.setBounds(183, 357, 184, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("  Mot de passe :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(22, 423, 98, 15);
        jPanel3.add(pwd);
        pwd.setBounds(183, 421, 184, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("  Date de Naissance :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(22, 478, 126, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("   Adresse : ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 579, 72, 15);
        jPanel3.add(adresse);
        adresse.setBounds(180, 559, 184, 73);

        valider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valider.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\valider.png")); // NOI18N
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                validerMouseReleased(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        jPanel3.add(valider);
        valider.setBounds(520, 619, 122, 38);

        tprenom.setBackground(new java.awt.Color(255, 0, 0));
        tprenom.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tprenom);
        tprenom.setBounds(180, 290, 175, 10);

        tcin.setBackground(new java.awt.Color(255, 0, 0));
        tcin.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tcin);
        tcin.setBounds(183, 335, 176, 10);

        tlogin.setBackground(new java.awt.Color(255, 0, 0));
        tlogin.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tlogin);
        tlogin.setBounds(183, 387, 166, 10);

        tpwd.setBackground(new java.awt.Color(255, 0, 0));
        tpwd.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tpwd);
        tpwd.setBounds(183, 442, 184, 10);

        tdate.setBackground(new java.awt.Color(255, 0, 0));
        tdate.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tdate);
        tdate.setBounds(180, 510, 176, 10);

        tadresse.setBackground(new java.awt.Color(255, 0, 0));
        tadresse.setForeground(new java.awt.Color(255, 51, 0));
        jPanel3.add(tadresse);
        tadresse.setBounds(0, 0, 0, 0);
        jPanel3.add(date);
        date.setBounds(180, 479, 190, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeineb\\Desktop\\pattiserie\\acceuille.jpg")); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 860, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addGap(251, 251, 251)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RBRespoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBRespoActionPerformed
        if (RBRespo.isSelected()) {
            jPanel2.setVisible(true);
            RBClient.setEnabled(false);
        } else {
            jPanel2.setVisible(false);
            RBClient.setEnabled(true);
        }
    }//GEN-LAST:event_RBRespoActionPerformed

    private void RBClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBClientActionPerformed
        if (RBClient.isSelected()) {
            jPanel2.setVisible(false);
            RBRespo.setEnabled(false);
        } else {
            RBRespo.setEnabled(true);
        }

    }//GEN-LAST:event_RBClientActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        int test = 0;
        if (RBClient.isSelected()) {
            IClientDAO pdao = new ClientDAO();
            PersonneDAO cdao = new PersonneDAO();
            int resultat = 0;

            Client p = new Client();
            tnom.setText("");
            tprenom.setText("");
            tcin.setText("");
            tlogin.setText("");
            tpwd.setText("");
            tdate.setText("");
            tadresse.setText("");
            if (nom.getText().equals("")) {
                tnom.setText("champ invalide");
            } else {
                if (isInteger(nom.getText())) {
                    tnom.setText("saisie chaine");
                } else {
                    p.setNom(nom.getText());
                    test++;
                }
            }
            if (prenom.getText().equals("")) {
                tprenom.setText("champs invalide");
            } else {
                if (isInteger(prenom.getText())) {
                    tprenom.setText("saisie  chaine");
                } else {
                    p.setPrenom(prenom.getText());
                    test++;
                }
            }
            if (cin.getText().equals("")) {
                tcin.setText("champs invalide");
            } else {
                if (!isInteger(cin.getText())) {
                    tcin.setText("saisie num");
                } else {
                    test++;
                    p.setCin(Integer.parseInt(cin.getText()));
                }
            }
            if (adresse.getText().equals("")) {
                tadresse.setText("champs invalide");
            } else {
                test++;
                p.setAdresse(adresse.getText());
            }
            if (login.getText().equals("")) {
                tlogin.setText("champs invalide");
            } else {

                resultat = cdao.trouverIdPersonneParLogin(login.getText());
                if (resultat != 0) {
                    JOptionPane.showMessageDialog(rootPane, "Utilisateur déja existant");
                } else {
                    test++;
                    p.setLogin(login.getText());
                }

            }
            if (pwd.getText().equals("")) {
                tpwd.setText("champs invalide");
            } else {
                test++;
                p.setPwd(pwd.getText());
            }
            System.out.println(test);
            if (test == 6) {
                java.util.Date utilDate = date.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                p.setDateNaissance(sqlDate);
                pdao.ajouterClient(p);

                JOptionPane.showMessageDialog(rootPane, "Client ajoutée avec succès");
            }

        }
        else if (RBRespo.isSelected())
        {
            ResponsablePatisserieDAO rdao = new  ResponsablePatisserieDAO();
            PersonneDAO cdao = new PersonneDAO();
            int resultat = 0;

          ResponsablePatisserie rp = new ResponsablePatisserie();
            tnom.setText("");
            tprenom.setText("");
            tcin.setText("");
            tlogin.setText("");
            tpwd.setText("");
            tdate.setText("");
            tadresse.setText("");
            tnomP.setText("");
            tadressep.setText("");
            if (nom.getText().equals("")) {
                tnom.setText("champ invalide");
            } else {
                if (isInteger(nom.getText())) {
                    tnom.setText("saisie chaine");
                } else {
                    rp.setNom(nom.getText());
                    test++;
                }
            }
            if (prenom.getText().equals("")) {
                tprenom.setText("champs invalide");
            } else {
                if (isInteger(prenom.getText())) {
                    tprenom.setText("saisie chaine");
                } else {
                    rp.setPrenom(prenom.getText());
                    test++;
                }
            }
            if (cin.getText().equals("")) {
                tcin.setText("champs invalide");
            } else {
                if (!isInteger(cin.getText())) {
                    tcin.setText("saisie num");
                } else {
                    test++;
                    rp.setCin(Integer.parseInt(cin.getText()));
                }
            }
            if (adresse.getText().equals("")) {
                tadresse.setText("champs invalide");
            } else {
                test++;
                rp.setAdresse(adresse.getText());
            }
            if (login.getText().equals("")) {
                tlogin.setText("champs invalide");
            } else {

                resultat = cdao.trouverIdPersonneParLogin(login.getText());
                if (resultat != 0) {
                    JOptionPane.showMessageDialog(rootPane, "Utilisateur déja existant");
                } else {
                    test++;
                    rp.setLogin(login.getText());
                }

            }
            if (pwd.getText().equals("")) {
                tpwd.setText("champs invalide");
            } else {
                test++;
                rp.setPwd(pwd.getText());
            }
            
             if (nomPatisserie.getText().equals("")) {
                tnomP.setText("champ invalide");
            } else {
                if (isInteger(nomPatisserie.getText())) {
                    tnomP.setText("saisie chaine");
                } else {
                   rp.setNom_patisserie(nomPatisserie.getText());
                    test++;
                }
            }
              if (adressepatisserie.getText().equals("")) {
                tadressep.setText("champs invalide");
            } else {
                test++;
                rp.setAdresse_Patisserie(adressepatisserie.getText());
               
            }
             
             
            System.out.println(test);
            if (test == 8) {
                java.util.Date utilDate = date.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                rp.setDateNaissance(sqlDate);
               rdao.insertResponsablePatisserie(rp);
                JOptionPane.showMessageDialog(rootPane, "Responsable Patisserie ajoutée avec succès");
            }
   
        }
        
        
        

       //nom.setEnabled(false);

    }//GEN-LAST:event_validerActionPerformed

    private void adressePatisserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressePatisserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressePatisserieActionPerformed

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void validerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_validerMouseReleased

    private void nomPatisserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPatisserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomPatisserieActionPerformed

    private void adressepatisserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressepatisserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressepatisserieActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void prenomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseEntered

// TODO add your handling code here:
    }//GEN-LAST:event_prenomMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                                       UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");


            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompteClient().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBClient;
    private javax.swing.JRadioButton RBRespo;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField adressePatisserie;
    private javax.swing.JTextField adressepatisserie;
    private javax.swing.JTextField cin;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomPatisserie;
    private javax.swing.JTextField nompatisserie;
    private javax.swing.JTextField prenom;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JLabel tadresse;
    private javax.swing.JLabel tadressep;
    private javax.swing.JLabel tcin;
    private javax.swing.JLabel tdate;
    private javax.swing.JLabel tlogin;
    private javax.swing.JLabel tnom;
    private javax.swing.JLabel tnomP;
    private javax.swing.JLabel tprenom;
    private javax.swing.JLabel tpwd;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
