/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.CatalogueD;
import edu.esprit.sweet4u.entites.Article;
import edu.esprit.sweet4u.entites.Catalogue;
import edu.esprit.sweet4u.util.MyConnection;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Nassoura
 */
public class CrudCatalogue extends javax.swing.JFrame {

    /**
     * Creates new form CrudCatalogue
     */
     public static String a;
    Connection cnx;
     AbstractTableModel model;
      private Catalogue k=new Catalogue();
    private static final String homeimg="C:\\Users\\Lenovo-G510\\Dropbox\\ESPRIT\\AlphaTech\\Sweet4U\\Sweet4u 2.0\\Sweet4U\\src\\image\\swwet.jpg";
    public CrudCatalogue() {
        initComponents();
        cnx = MyConnection.getInstance();
        RefineryUtilities.centerFrameOnScreen(this);
        model=(AbstractTableModel)jTable1.getModel();
        tfimage.setIcon(new ImageIcon(homeimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JButton();
        tfimage = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ajouterCatalogue = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ajouterArticle = new javax.swing.JButton();
        refrech = new javax.swing.JButton();
        Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gestion Catalogue");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 210, 50));

        image.setText("Parcourir Image Folder");
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 30));
        getContentPane().add(tfimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 220, 190));
        getContentPane().add(tfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        jLabel2.setText("Nom Catalogue");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        ajouterCatalogue.setText("ajouter catalogue");
        ajouterCatalogue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ajouterCatalogueMouseReleased(evt);
            }
        });
        ajouterCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterCatalogueActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 150, -1));

        modifier.setText("Modifier Catalogue");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 150, -1));

        supprimer.setText("supprimer Ctalogue");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 150, -1));

        jTable1.setModel(new tablCatalogue());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 130));

        ajouterArticle.setText("ajouter articles de catalogue");
        ajouterArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterArticleActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        refrech.setText("refresh");
        refrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrechActionPerformed(evt);
            }
        });
        getContentPane().add(refrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        getContentPane().add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "gif","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String s=chooser.getSelectedFile().getPath();

            k.setLien(s);
            tfimage.setIcon(new ImageIcon(s));

        }
    }//GEN-LAST:event_imageActionPerformed

    private void ajouterCatalogueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterCatalogueMouseReleased

    }//GEN-LAST:event_ajouterCatalogueMouseReleased

    private void ajouterCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterCatalogueActionPerformed
        CatalogueD cDAO = new CatalogueD();
        if (tfNom.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " Champ catalogue est vide!!!!!!!");}
        else {
            int  resultat = cDAO.trouverIdCatalogueParNom(tfNom.getText());
            if (resultat != 0) {
                JOptionPane.showMessageDialog(rootPane, "Catalogue déja existant");
            }
            else{
                String NomCatalogue = tfNom.getText();

                k.setNom(NomCatalogue);
                cDAO.ajouterCatalogue(k);
                JOptionPane.showMessageDialog(this, " catalogue ajouté");
                tablCatalogue tablcatal = new  tablCatalogue();
                jTable1.setModel( tablcatal);
                tablcatal.fireTableDataChanged();
                model=(AbstractTableModel)jTable1.getModel();
                tfNom.setText(null);
                
            }
         tfimage.setIcon(new ImageIcon(homeimg));}
    }//GEN-LAST:event_ajouterCatalogueActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        CatalogueD cDAO = new CatalogueD();

        try {
              
            String nom = model.getValueAt(jTable1.getSelectedRow(),0).toString();

            k.setNom(tfNom.getText());
            k.setLien(tfimage.getIcon().toString());
            System.out.println(k);
            int idCa=cDAO.trouverIdCatalogueParNom(nom);
            cDAO.modifierCatalogue(k,idCa);
            JOptionPane.showMessageDialog(null, "Catalogue modifié avec succés");
            tfNom.setText(null);

            tablCatalogue tablcatal = new  tablCatalogue();
            jTable1.setModel( tablcatal);
            tablcatal.fireTableDataChanged();
            model=(AbstractTableModel)jTable1.getModel();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un catalogue ");
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        CatalogueD cDAO = new CatalogueD();

        try {
            String a  =   model.getValueAt(jTable1.getSelectedRow(),0).toString();
            int idC= cDAO.trouverIdCatalogueParNom(a);
            Catalogue catalog = new Catalogue();
            Article arti=new Article();
            cDAO.supprimerCatalogue(catalog,idC);
            cDAO.supprimerArticleDuCatalogue(arti, idC);
            tablCatalogue tablcatal = new  tablCatalogue();
            jTable1.setModel( tablcatal);
            tablcatal.fireTableDataChanged();
            model=(AbstractTableModel)jTable1.getModel();
            tfNom.setText(null);
            tfimage.setIcon(new ImageIcon());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un catalogue ");
        }

    }//GEN-LAST:event_supprimerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        CatalogueD cDAO = new CatalogueD();
        tfNom.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(),0)));

        String kar  =   model.getValueAt(jTable1.getSelectedRow(),0).toString();
        int idC= cDAO.trouverIdCatalogueParNom(kar);
        String s =  cDAO.trouverCatalogueParId(idC).getLien();

        if (!s.isEmpty() || !s.equals(null))
        tfimage.setIcon(new ImageIcon(s));
        else
        tfimage.setIcon(new ImageIcon(homeimg));
    }//GEN-LAST:event_jTable1MouseClicked

    private void ajouterArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterArticleActionPerformed
        try {
            int rowS = jTable1.getSelectedRow();
            String nom = jTable1.getModel().getValueAt(rowS, 0).toString();
            CatalogueD cdao = new CatalogueD();
            int id_C = cdao.trouverIdCatalogueParNom(nom);
            CrudArticle C = new CrudArticle(id_C);
            this.setVisible(false);
            C.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez choisir un catalogue ");
        }
    }//GEN-LAST:event_ajouterArticleActionPerformed

    private void refrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrechActionPerformed
        // TODO add your handling code here:
        CrudCatalogue catalogue=new CrudCatalogue();
        catalogue.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refrechActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
        AcceuilResponsablePatisserie acceuil=new AcceuilResponsablePatisserie();
        acceuil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudCatalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JButton ajouterArticle;
    private javax.swing.JButton ajouterCatalogue;
    private javax.swing.JButton image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton refrech;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField tfNom;
    private javax.swing.JLabel tfimage;
    // End of variables declaration//GEN-END:variables
}
