/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.sweet4u.GUI;

import edu.esprit.sweet4u.DAO.ArticleDAO;
import edu.esprit.sweet4u.entites.Article;
import edu.esprit.sweet4u.util.MyConnection;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Nassoura
 */
public class CrudArticle extends javax.swing.JFrame {

    /**
     * Creates new form CrudArticle
     */
     int id_C;
    int id_A;
    Connection cnx;
    AbstractTableModel model;
    public CrudArticle() {
        initComponents();
    }
 public CrudArticle(int id ) {
         initComponents();
         this.id_C=id;
         cnx = MyConnection.getInstance();
          RefineryUtilities.centerFrameOnScreen(this);
         model=(AbstractTableModel)jTable1.getModel();
         
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNom = new javax.swing.JTextField();
        tfPrix = new javax.swing.JTextField();
        tfPromo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        retour = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, -1));
        getContentPane().add(tfPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, -1));

        tfPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPromoActionPerformed(evt);
            }
        });
        getContentPane().add(tfPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        jLabel2.setText("Nom article");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 68, -1, -1));

        jLabel3.setText("Prix");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 103, 54, -1));

        jLabel4.setText("Prix_Promo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 144, -1, -1));

        jTable1.setModel(new tablArticle());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 420, 240));

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        ajouter.setText("ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        modifier.setText("modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        supprimer.setText("supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPromoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tfNom.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(),0)));
        tfPrix.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(),1)));
        tfPromo.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(),2)));

    }//GEN-LAST:event_jTable1MouseClicked

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        CrudCatalogue catalogue=new CrudCatalogue();
        catalogue.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        model=(AbstractTableModel)jTable1.getModel();

        CrudArticle C = new CrudArticle(id_C);
        this.setVisible(false);
        C.setVisible(true);

    }//GEN-LAST:event_refreshActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        ArticleDAO aDAO = new ArticleDAO();
        if (tfNom.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " Champ Nom est vide!!!!!!!");}
        else if ( !tfNom.getText().matches("^[a-zA-Z- ]*$")) {
            JOptionPane.showMessageDialog(this, " Champ Nom n'est pas une chaine de caractère!!!!!!!");}
        else if (tfPrix.getText().trim().equals("") ) {
            JOptionPane.showMessageDialog(this, " Champ Prix est vide!!!!!!!");}
        else if (!tfPrix.getText().matches("[+|-|0]?[0-9]+(.[0-9]*)?")) {
            JOptionPane.showMessageDialog(this, " Champ Prix n'est pas un nombre!!!!!!!");}
        else if (tfPromo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, " Champ Prix promo est vide!!!!!!!");}

        else {

            float p=Float.parseFloat(tfPrix.getText());
            float pro=Float.parseFloat(tfPromo.getText());
            Article a = new Article(tfNom.getText(),p,pro);
            a.setNom(tfNom.getText());
            a.setPrix(p);
            a.setPrixPromo(pro);
            a.setIdCatalogue(id_C);
            aDAO.ajouterArticle(a);
            JOptionPane.showMessageDialog(this, " article ajouté");
            tablArticle tablarticle = new  tablArticle();
            jTable1.setModel( tablarticle);
            tablarticle.fireTableDataChanged();
            model=(AbstractTableModel)jTable1.getModel();
            tfNom.setText(null);
            tfPrix.setText(null);
            tfPromo.setText(null);
        }
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        ArticleDAO aDAO = new ArticleDAO();
        try {
            String nom = model.getValueAt(jTable1.getSelectedRow(),0).toString();
            Article art = new Article();
            float p=Float.parseFloat(tfPrix.getText());
            float pro=Float.parseFloat(tfPromo.getText());
            art.setNom(tfNom.getText());
            art.setPrix(p);
            art.setPrixPromo(pro);
            System.out.println(art);
            aDAO.trouverIdArticleParNom(nom);
            aDAO.modifierArticle(art, nom);
            JOptionPane.showMessageDialog(null, "Article modifié avec succés");
            tfNom.setText(null);
            tfPrix.setText(null);
            tfPromo.setText(null);

            tablArticle tablarticle = new  tablArticle();
            jTable1.setModel( tablarticle);
            tablarticle.fireTableDataChanged();
            model=(AbstractTableModel)jTable1.getModel();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un article ");

        }

    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        ArticleDAO aDAO = new ArticleDAO();
        try {
            String a  =   model.getValueAt(jTable1.getSelectedRow(),0).toString();
            int id_A = aDAO.trouverIdArticleParNom(a);
            aDAO.supprimerArticle(a);
            tablArticle tablarticle = new  tablArticle();
            jTable1.setModel( tablarticle);
            tablarticle.fireTableDataChanged();
            model=(AbstractTableModel)jTable1.getModel();
            tfNom.setText(null);
            tfPrix.setText(null);
            tfPromo.setText(null);}
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, " Veuillez selectionez un article ");

        }

    }//GEN-LAST:event_supprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton refresh;
    private javax.swing.JButton retour;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfPromo;
    // End of variables declaration//GEN-END:variables
}
